[package]
name = "kev-core"
version = "0.2.1"
edition = "2024"
description = "Cactus Kev's 32-bit card integer library for Rust"
license = "LGPL-3.0-only"
repository = "https://github.com/soltez/kev-core"

[dependencies]

[lib]
name = "kev_core"

[dev-dependencies]
rstest = "0.25"

[profile.release]
opt-level = 3
